export const Types = {
  GOAL_GET_REQUEST: 'GOAL_GET_REQUEST',
  GOAL_GET_SUCCESS: 'GOAL_GET_SUCCESS',
  GOAL_GET_FAILURE: 'GOAL_GET_SUCCESS',

  SETPS_GET_REQUEST: 'SETPS_GET_REQUEST',
  SETPS_GET_SUCCESS: 'SETPS_GET_SUCCESS',
  SETPS_GET_FAILURE: 'SETPS_GET_FAILURE',

  USER_SET_GOAL: 'USER_SET_GOAL',
  USER_SET_HEIGHT: 'USER_SET_HEIGHT',
  USER_SET_AGE: 'USER_SET_AGE',
};

