export const Types = {
  GOAL_GET_REQUEST: 'GOAL_GET_REQUEST',
  GOAL_GET_SUCCESS: 'GOAL_GET_SUCCESS',
  GOAL_GET_FAILURE: 'GOAL_GET_SUCCESS',

  STEPS_GET_REQUEST: 'STEPS_GET_REQUEST',
  STEPS_GET_SUCCESS: 'STEPS_GET_SUCCESS',
  STEPS_GET_FAILURE: 'STEPS_GET_FAILURE',
  STEPS_GO_BACK: 'STEPS_GO_BACK',
  STEPS_GO_NEXT: 'STEPS_GO_NEXT',

  USER_SET_GOAL: 'USER_SET_GOAL',
  USER_SET_HEIGHT: 'USER_SET_HEIGHT',
  USER_SET_AGE: 'USER_SET_AGE',
};

